export enum DiagnosticReportStatus {
  REGISTERED = 'REGISTERED',

  PARTIAL = 'PARTIAL',

  PRELIMINARY = 'PRELIMINARY',

  MODIFIED = 'MODIFIED',

  FINAL = 'FINAL',

  AMENDED = 'AMENDED',

  CORRECTED = 'CORRECTED',

  APPENDED = 'APPENDED',

  CANCELLED = 'CANCELLED',

  ENTERED_IN_ERROR = 'ENTERED_IN_ERROR',

  UNKNOWN = 'UNKNOWN',
}
